markdown: kramdown

name: Ohlasy
description: 'Internetové noviny pro Boskovice a okolí'
url: 'http://ohlasy.info'

permalink: '/clanky/:year/:month/:title.html'
paginate_path: "/clanky/strana/:num"
paginate: 6

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'article'

future: false
exclude: ['README.md', 'Gemfile*', 'CNAME', 'vendor']
