markdown: kramdown

name: Ohlasy
description: 'Noviny pro Boskovice a okolí'
url: 'http://ohlasy.info'

collections:
  special:
    output: true
    permalink: /:collection/:path.html

permalink: '/clanky/:year/:month/:title.html'

jekyll_get:
  data: nejctenejsi
  json: 'http://data.ohlasy.info/top-articles.json'

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: 'article'
  -
    scope:
      path: ''
      type: special
    values:
      layout: 'volby2016'

future: false
exclude: ['README.md', 'Gemfile*', 'CNAME', 'vendor', 'package.json', 'Makefile', 's3_website.yml']

# https://talk.jekyllrb.com/t/324
array: []
