markdown: kramdown

name: Ohlasy
description: "Noviny pro Boskovice a okolí"
url: "http://ohlasy.info"

permalink: "/clanky/:year/:month/:title.html"

jekyll_get:
  - data: nejctenejsi
    json: "https://data.ohlasy.info/stats/top-articles.json"
  - data: forum
    json: "https://forum.ohlasy.info/latest.json"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "article"

future: false
exclude: ["README.md", "Gemfile*", "package.json", "vercel.json", "yarn.lock"]

# https://talk.jekyllrb.com/t/324
array: []
