markdown: kramdown

name: Ohlasy
description: 'Internetové noviny pro Boskovice a okolí'
url: 'http://ohlasy.info'

collections:
  special:
    output: true
    permalink: /:collection/:path.html

gems: ['jekyll-paginate']

permalink: '/clanky/:year/:month/:title.html'
paginate_path: "/clanky/strana/:num"
paginate: 7

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: 'article'
  -
    scope:
      path: ''
      type: special
    values:
      layout: 'volby2016'

future: false
exclude: ['README.md', 'Gemfile*', 'CNAME', 'vendor', 'bower.json', 'Makefile']

# https://talk.jekyllrb.com/t/324
array: []
