# Allow loading resources under /api from anywhere
[[headers]]
    for = "/api/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
[[headers]]
    for = "/static-api/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"

# We didn’t choose the initial podcast URLs very well,
# so we moved them later and redirect the older locations.
[[redirects]]
    from = "/podcast.xml"
    to = "/podcast/feed.xml"
[[redirects]]
    from = "/podcast.html"
    to = "/podcast/"

[[redirects]]
    from = "/odpady.ics"
    to = "https://calendar.google.com/calendar/ical/66le85f8os6tp1fnf8k2mtfunc%40group.calendar.google.com/public/basic.ics"
